import type { JobApi, JobEventApi } from "./schemas";

const DEMO_WORKSPACE_ID_VALUE = "demo-workspace";

const now = new Date();

const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString();

export const DUMMY_JOBS: JobApi[] = [
  {
    id: "job-demo-001",
    userId: "user-demo",
    companyId: null,
    company: { id: "company-001", name: "Acme Robotics", domain: "acme.com" },
    title: "Senior Robotics Engineer",
    location: "San Francisco, CA",
    remote: true,
    employment: "FULL_TIME",
    salaryMin: 180000,
    salaryMax: 220000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    status: "SAVED",
    sourceKind: "LINKEDIN",
    sourceId: "123456",
    jobUrl: "https://jobs.acme.com/senior-robotics",
    canonicalHash: null,
    jdText:
      "You will design motion planning algorithms and collaborate with cross-functional teams to bring autonomous systems to market.",
    tags: ["ROBOTICS", "PYTHON", "ROS"],
    notes: "Reach out to recruiter after lunch.",
    boardOrder: 0,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
    savedAt: daysAgo(6),
    appliedAt: null,
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    metadata: { workspaceId: DEMO_WORKSPACE_ID_VALUE, resumeVariantLabel: "Robotics Resume" },
  },
  {
    id: "job-demo-002",
    userId: "user-demo",
    companyId: null,
    company: { id: "company-002", name: "Nimbus Cloud", domain: "nimbus.io" },
    title: "Staff Platform Engineer",
    location: "Remote - US",
    remote: true,
    employment: "FULL_TIME",
    salaryMin: 200000,
    salaryMax: 240000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    status: "APPLIED",
    sourceKind: "GREENHOUSE",
    sourceId: "nimbus-789",
    jobUrl: "https://jobs.nimbus.io/platform-engineer",
    canonicalHash: null,
    jdText:
      "Own critical portions of the platform, drive reliability, and mentor engineers across the org.",
    tags: ["PLATFORM", "KUBERNETES", "GOLANG"],
    notes: "Applied with platform resume; recruiter will follow up next Monday.",
    boardOrder: 0,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
    savedAt: daysAgo(12),
    appliedAt: daysAgo(3),
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    metadata: { workspaceId: DEMO_WORKSPACE_ID_VALUE, resumeVariantLabel: "Platform Resume" },
  },
  {
    id: "job-demo-003",
    userId: "user-demo",
    companyId: null,
    company: { id: "company-003", name: "Helios Energy", domain: "helios.energy" },
    title: "Lead Data Scientist",
    location: "Austin, TX",
    remote: false,
    employment: "FULL_TIME",
    salaryMin: 170000,
    salaryMax: 210000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    status: "INTERVIEW",
    sourceKind: "LEVER",
    sourceId: "helios-456",
    jobUrl: "https://helios.energy/careers/data-scientist",
    canonicalHash: null,
    jdText:
      "Drive forecasting models for the energy grid and partner with product to launch insights dashboards.",
    tags: ["PYTHON", "ML", "FORECASTING"],
    notes: "Prep analytics leadership interview; review energy domain KPIs.",
    boardOrder: 0,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
    savedAt: daysAgo(20),
    appliedAt: daysAgo(15),
    interviewAt: daysAgo(1),
    offerAt: null,
    rejectedAt: null,
    metadata: { workspaceId: DEMO_WORKSPACE_ID_VALUE, resumeVariantLabel: "Data Resume" },
  },
  {
    id: "job-demo-004",
    userId: "user-demo",
    companyId: null,
    company: { id: "company-004", name: "Lumen Labs", domain: "lumenlabs.ai" },
    title: "AI Product Manager",
    location: "New York, NY",
    remote: true,
    employment: "FULL_TIME",
    salaryMin: 160000,
    salaryMax: 190000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    status: "OFFER",
    sourceKind: "WORKDAY",
    sourceId: "lumen-111",
    jobUrl: "https://lumenlabs.ai/careers/pm-ai",
    canonicalHash: null,
    jdText:
      "Lead cross-functional teams to ship AI-powered analytics features and own product discovery.",
    tags: ["PRODUCT", "AI", "ROADMAP"],
    notes: "Offer received, negotiating equity. Compare with Nimbus role.",
    boardOrder: 0,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(0.5),
    savedAt: daysAgo(25),
    appliedAt: daysAgo(18),
    interviewAt: daysAgo(5),
    offerAt: daysAgo(0.5),
    rejectedAt: null,
    metadata: { workspaceId: DEMO_WORKSPACE_ID_VALUE, resumeVariantLabel: "Product Resume" },
  },
  {
    id: "job-demo-005",
    userId: "user-demo",
    companyId: null,
    company: { id: "company-005", name: "Aurora Biotech", domain: "aurorabiotech.com" },
    title: "Senior DevOps Engineer",
    location: "Boston, MA",
    remote: false,
    employment: "FULL_TIME",
    salaryMin: 150000,
    salaryMax: 180000,
    salaryCurrency: "USD",
    salaryPeriod: "YEAR",
    status: "REJECTED",
    sourceKind: "INDEED",
    sourceId: "aurora-555",
    jobUrl: "https://aurorabiotech.com/careers/devops",
    canonicalHash: null,
    jdText:
      "Support hybrid cloud infrastructure, implement CI/CD, and partner with research teams for deployments.",
    tags: ["DEVOPS", "AWS", "CI/CD"],
    notes: "Received polite rejection; ask for feedback next week.",
    boardOrder: 0,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
    savedAt: daysAgo(40),
    appliedAt: daysAgo(32),
    interviewAt: daysAgo(20),
    offerAt: null,
    rejectedAt: daysAgo(10),
    metadata: { workspaceId: DEMO_WORKSPACE_ID_VALUE, resumeVariantLabel: "DevOps Resume" },
  },
];

export const DUMMY_EVENTS: Record<string, JobEventApi[]> = {
  "job-demo-001": [
    {
      id: "evt-001",
      jobId: "job-demo-001",
      userId: "user-demo",
      kind: "CREATED",
      message: "Job saved from LinkedIn",
      metadata: null,
      createdAt: daysAgo(6),
    },
  ],
  "job-demo-002": [
    {
      id: "evt-010",
      jobId: "job-demo-002",
      userId: "user-demo",
      kind: "CREATED",
      message: "Job saved",
      metadata: null,
      createdAt: daysAgo(12),
    },
    {
      id: "evt-011",
      jobId: "job-demo-002",
      userId: "user-demo",
      kind: "UPDATED",
      message: "Resume variant: Platform Resume",
      metadata: null,
      createdAt: daysAgo(4),
    },
    {
      id: "evt-012",
      jobId: "job-demo-002",
      userId: "user-demo",
      kind: "APPLIED",
      message: "Applied via Greenhouse",
      metadata: null,
      createdAt: daysAgo(3),
    },
  ],
  "job-demo-003": [
    {
      id: "evt-020",
      jobId: "job-demo-003",
      userId: "user-demo",
      kind: "CREATED",
      message: "Imported from Lever",
      metadata: null,
      createdAt: daysAgo(20),
    },
    {
      id: "evt-021",
      jobId: "job-demo-003",
      userId: "user-demo",
      kind: "STATUS_CHANGE",
      message: "Advanced to interview stage",
      metadata: { from: "APPLIED", to: "INTERVIEW" },
      createdAt: daysAgo(2),
    },
    {
      id: "evt-022",
      jobId: "job-demo-003",
      userId: "user-demo",
      kind: "AUTOFILL",
      message: "Auto-filled Helios screening form",
      metadata: null,
      createdAt: daysAgo(1),
    },
  ],
  "job-demo-004": [
    {
      id: "evt-030",
      jobId: "job-demo-004",
      userId: "user-demo",
      kind: "CREATED",
      message: "Job saved from referral",
      metadata: null,
      createdAt: daysAgo(25),
    },
    {
      id: "evt-031",
      jobId: "job-demo-004",
      userId: "user-demo",
      kind: "STATUS_CHANGE",
      message: "Advanced to offer stage",
      metadata: { from: "INTERVIEW", to: "OFFER" },
      createdAt: daysAgo(0.5),
    },
  ],
  "job-demo-005": [
    {
      id: "evt-040",
      jobId: "job-demo-005",
      userId: "user-demo",
      kind: "CREATED",
      message: "Job saved via Indeed",
      metadata: null,
      createdAt: daysAgo(40),
    },
    {
      id: "evt-041",
      jobId: "job-demo-005",
      userId: "user-demo",
      kind: "STATUS_CHANGE",
      message: "Marked as rejected",
      metadata: { from: "INTERVIEW", to: "REJECTED" },
      createdAt: daysAgo(10),
    },
  ],
};

export const DEMO_WORKSPACE_ID = DEMO_WORKSPACE_ID_VALUE;
