import { addMinutes, subDays } from "./utils/date";
import type {
  EmploymentType,
  JobActivity,
  JobOpportunity,
  JobStage,
  WorkStyle,
} from "./types";

const createActivity = (
  label: string,
  value: string,
  type: JobActivity["type"] = "other",
): JobActivity => ({
  label,
  value,
  type,
});

const baseDate = new Date("2024-10-17T09:30:00");

const makeJob = (job: Partial<JobOpportunity> & Pick<JobOpportunity, "id">) => {
  const now = new Date();
  return {
    title: "Product Designer",
    company: "Acme",
    status: "saved" as JobStage,
    location: "Remote",
    workStyle: "Remote" as WorkStyle,
    employmentType: "Full Time" as EmploymentType,
    activities: [],
    tags: [],
    color: "#6366F1",
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    ...job,
  };
};

export const SEED_JOBS: JobOpportunity[] = [
  makeJob({
    id: "saved-1",
    title: "Principal UI/UX Designer",
    company: "Facebook",
    location: "Menlo Park, CA",
    status: "saved",
    compensation: {
      currency: "USD",
      min: 200000,
      max: 300000,
      cadence: "year",
    },
    workStyle: "Hybrid",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Saved on", baseDate.toISOString(), "other"),
      createActivity("Next follow up", addMinutes(baseDate, 240).toISOString()),
    ],
    color: "#2563EB",
  }),
  makeJob({
    id: "saved-2",
    title: "Senior Interaction Designer",
    company: "Zoom",
    location: "Menlo Park, CA",
    status: "saved",
    compensation: {
      currency: "USD",
      min: 200000,
      max: 300000,
      cadence: "year",
    },
    tags: ["Remote", "Full Time"],
    activities: [createActivity("Saved on", baseDate.toISOString())],
    color: "#0EA5E9",
  }),
  makeJob({
    id: "saved-3",
    title: "UI/UX Designer",
    company: "Taobao",
    location: "Menlo Park, CA",
    status: "saved",
    compensation: {
      currency: "USD",
      min: 190000,
      max: 280000,
      cadence: "year",
    },
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Saved on", baseDate.toISOString()),
      createActivity("Reminder", addMinutes(baseDate, 360).toISOString()),
    ],
    color: "#F97316",
  }),
  makeJob({
    id: "saved-4",
    title: "Senior Lead Designer",
    company: "Reddit",
    location: "Menlo Park, CA",
    status: "saved",
    tags: ["Remote", "Full Time"],
    activities: [createActivity("Saved on", baseDate.toISOString())],
    color: "#FB923C",
  }),
  makeJob({
    id: "saved-5",
    title: "Principal UI/UX Designer Manager",
    company: "Opera",
    location: "Remote",
    status: "saved",
    tags: ["Remote", "Full Time"],
    activities: [createActivity("Saved on", baseDate.toISOString())],
    color: "#EF4444",
  }),
  makeJob({
    id: "saved-6",
    title: "UI/UX Designer Manager",
    company: "Google",
    location: "Menlo Park, CA",
    status: "saved",
    tags: ["Remote", "Full Time"],
    activities: [createActivity("Saved on", baseDate.toISOString())],
    color: "#22C55E",
  }),
  makeJob({
    id: "applied-1",
    title: "UI/UX Designer Manager",
    company: "Mailchimp",
    location: "Remote",
    status: "applied",
    compensation: {
      currency: "USD",
      min: 200000,
      max: 300000,
      cadence: "year",
    },
    tags: ["Remote", "Full Time"],
    appliedAt: subDays(baseDate, 1).toISOString(),
    activities: [
      createActivity("Applied", subDays(baseDate, 1).toISOString(), "applied"),
    ],
    color: "#F59E0B",
  }),
  makeJob({
    id: "applied-2",
    title: "Sr. UI/UX Manager",
    company: "Intercom",
    location: "Remote",
    status: "applied",
    compensation: {
      currency: "USD",
      min: 210000,
      max: 305000,
      cadence: "year",
    },
    tags: ["Remote", "Full Time"],
    appliedAt: subDays(baseDate, 2).toISOString(),
    activities: [
      createActivity("Applied", subDays(baseDate, 2).toISOString(), "applied"),
      createActivity("Follow up", addMinutes(baseDate, 60).toISOString()),
    ],
    color: "#6366F1",
  }),
  makeJob({
    id: "applied-3",
    title: "Front-end Developer",
    company: "Asana",
    location: "Remote",
    status: "applied",
    tags: ["Remote", "Full Time"],
    appliedAt: baseDate.toISOString(),
    activities: [
      createActivity("Applied", baseDate.toISOString(), "applied"),
      createActivity("Note", "UI handshake with hiring manager", "note"),
    ],
    color: "#F97316",
  }),
  makeJob({
    id: "applied-4",
    title: "Principal UI/UX Designer",
    company: "Asana",
    location: "Remote",
    status: "applied",
    tags: ["Remote", "Full Time"],
    appliedAt: baseDate.toISOString(),
    activities: [
      createActivity("Applied", baseDate.toISOString(), "applied"),
      createActivity("Reminder", addMinutes(baseDate, 90).toISOString()),
    ],
    color: "#EC4899",
  }),
  makeJob({
    id: "interview-1",
    title: "Backend Developer",
    company: "Youtube",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    appliedAt: subDays(baseDate, 5).toISOString(),
    followUpAt: addMinutes(baseDate, 180).toISOString(),
    activities: [
      createActivity("Applied", subDays(baseDate, 5).toISOString(), "applied"),
      createActivity(
        "Interview",
        addMinutes(baseDate, 90).toISOString(),
        "interview",
      ),
    ],
    color: "#DC2626",
  }),
  makeJob({
    id: "interview-2",
    title: "UI/UX Designer Manager",
    company: "Pinterest",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 180).toISOString(),
        "interview",
      ),
    ],
    color: "#F87171",
  }),
  makeJob({
    id: "interview-3",
    title: "UI/UX Designer Manager",
    company: "Ubuntu",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 120).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 120).toISOString(),
        "interview",
      ),
    ],
    color: "#EF4444",
  }),
  makeJob({
    id: "interview-4",
    title: "UI/UX Designer Manager",
    company: "Snapchat",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 60).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 60).toISOString(),
        "interview",
      ),
    ],
    color: "#FACC15",
  }),
  makeJob({
    id: "interview-5",
    title: "UI/UX Designer Manager",
    company: "Whatsapp",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 600).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 600).toISOString(),
        "interview",
      ),
    ],
    color: "#22C55E",
  }),
  makeJob({
    id: "interview-6",
    title: "Senior Product Designer",
    company: "Stripe",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 300).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 300).toISOString(),
        "interview",
      ),
    ],
    color: "#4F46E5",
  }),
  makeJob({
    id: "interview-7",
    title: "Lead Product Designer",
    company: "Dropbox",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 420).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 420).toISOString(),
        "interview",
      ),
    ],
    color: "#38BDF8",
  }),
  makeJob({
    id: "interview-8",
    title: "Principal UX Researcher",
    company: "Figma",
    location: "Remote",
    status: "interviewing",
    tags: ["Remote", "Full Time"],
    followUpAt: addMinutes(baseDate, 510).toISOString(),
    activities: [
      createActivity(
        "Interview",
        addMinutes(baseDate, 510).toISOString(),
        "interview",
      ),
    ],
    color: "#A855F7",
  }),
  makeJob({
    id: "rejected-1",
    title: "UI/UX Designer",
    company: "Skrill",
    location: "Remote",
    status: "rejected",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Rejected", subDays(baseDate, 2).toISOString(), "other"),
    ],
    color: "#A855F7",
  }),
  makeJob({
    id: "rejected-2",
    title: "Principal UI/UX Designer",
    company: "Coinbase",
    location: "Remote",
    status: "rejected",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Rejected", subDays(baseDate, 3).toISOString(), "other"),
    ],
    color: "#2563EB",
  }),
  makeJob({
    id: "rejected-3",
    title: "Principal UI/UX Designer",
    company: "Line",
    location: "Remote",
    status: "rejected",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Rejected", subDays(baseDate, 1).toISOString(), "other"),
    ],
    color: "#22C55E",
  }),
  makeJob({
    id: "rejected-4",
    title: "UI/UX Designer",
    company: "OK",
    location: "Remote",
    status: "rejected",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Rejected", subDays(baseDate, 4).toISOString(), "other"),
    ],
    color: "#F97316",
  }),
  makeJob({
    id: "offer-1",
    title: "Lead UI/UX Designer",
    company: "Atlassian",
    location: "Remote",
    status: "offer",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Offer received", baseDate.toISOString(), "offer"),
    ],
    color: "#1D4ED8",
  }),
  makeJob({
    id: "offer-2",
    title: "Product UI/UX Designer Manager",
    company: "Microsoft",
    location: "Remote",
    status: "offer",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Offer received", baseDate.toISOString(), "offer"),
    ],
    color: "#2563EB",
  }),
  makeJob({
    id: "offer-3",
    title: "Principal UI/UX Designer Manager",
    company: "Gumroad",
    location: "Remote",
    status: "offer",
    tags: ["Remote", "Full Time"],
    activities: [
      createActivity("Offer received", baseDate.toISOString(), "offer"),
    ],
    color: "#9333EA",
  }),
];
